theme: jekyll-theme-minimal
logo: https://www.aljazeera.com/wp-content/uploads/2023/08/2023-08-06T174428Z_1832925064_UP1EJ861DA2QM_RTRMADP_3_SOCCER-ENGLAND-MCI-ARS-REPORT-1691344144.jpg?resize=770%2C513&quality=80
title: Bioinformatics

