---
title: "Class 6 Homework"
author: "Jason Hsiao (PID: A15871650)"
format: pdf
---

## Original Code:
```{r}
# Can you improve this analysis code?
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s1, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")

```

## Writing the Function
```{r}
library(bio3d) #loading bio3d package

#Compressing the original code to a function called 'visualize()', which iterates
#pdb accession files through the functions defined below
visualize <- function(x) {
  pdb <- read.pdb(x) #reading pdb file
  trim <- trim.pdb(pdb, chain = "A", elety = "CA") #removing metadata 
  atomb <- trim$atom$b #accessing atom level data
  plotb3(atomb, sse = trim, typ = "l", ylab = "Bfactor") #plotting bfactor

  }
  
```

## Testing, Testing, 1, 2, 3...
```{r}
#Output of the function, inputting pdb accession codes into function
visualize("4AKE")
visualize("1AKE")
visualize("1E4Y")
```

